package com.mapbox.rctmgl.events.constants

object StatusType {
    val ERROR_NO_ACCESS_TOKEN = "ERROR_NO_ACCESS_TOKEN"
    val ERROR_SIMULATION_NO_ORIGIN = "ERROR_SIMULATION_NO_ORIGIN"
    val ERROR_FIND_ROUTE_NO_ORIGIN = "ERROR_FIND_ROUTE_NO_ORIGIN"
    val ERROR_FIND_ROUTE_NO_DESTINATION = "ERROR_FIND_ROUTE_NO_DESTINATION"
    val ERROR_FIND_ROUTE_NO_ROUTES = "ERROR_FIND_ROUTE_NO_ROUTES"
    val ERROR_SEARCH_NO_RESULT_FOUND = "ERROR_SEARCH_NO_RESULT_FOUND"
    val ERROR_FIND_ROUTE_API = "ERROR_FIND_ROUTE_API"
    val ERROR_START_ROUTE_NO_ROUTES = "ERROR_START_ROUTE_NO_ROUTES"
    val ERROR_START_ROUTE_NO_DESTINATION = "ERROR_START_ROUTE_NO_DESTINATION"
    val ERROR_PERMISSION_LOCATION_REQUIRED = "ERROR_PERMISSION_LOCATION_REQUIRED"
    val SUCCESS = "SUCCESS"
}

object StatusCode {
    val ERROR_NO_ACCESS_TOKEN = 401
    val ERROR_SIMULATION_NO_ORIGIN = 402
    val ERROR_FIND_ROUTE_NO_ORIGIN = 403
    val ERROR_FIND_ROUTE_NO_DESTINATION = 404
    val ERROR_FIND_ROUTE_NO_ROUTES = 405
    val ERROR_FIND_ROUTE_API = 406
    val ERROR_SEARCH_NO_RESULT_FOUND = 407
    val ERROR_START_ROUTE_NO_ROUTES = 408
    val ERROR_START_ROUTE_NO_DESTINATION = 409
    val ERROR_PERMISSION_LOCATION_REQUIRED = 400
    val SUCCESS = 200
}